language: node_js
node_js:
  - "6"
os:
  - linux

before_install:
  - "export CHROME_BIN=chromium-browser"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
